Portfolio website responsive design
KMT-Media/Portfolio-setup-and-mobile-first pull request #5
Opened 2022-11-03 19:06 UTC by KMT-Media

In this pull request the following actions are implemented:
* Responsive design using media queries.
* Flexbox and CSS grid are used to lay out the elements inside the web page.

2022-11-03 20:38 UTC, bienvenuushindi requested changes
### Hi @KMT-Media ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif">

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linter checks are ok. ✔
- 

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- { ] N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
:red_circle:  Please make sure you move  `Glad to see you!` to a new line you can insert a` <br>` tag between `I'm Mariane` and `Glad to see you!` to insert a single line break. Your final code will look like this `I'm Mariane <br> Glad to see you!`

Your Design
![headertitle](https://user-images.githubusercontent.com/26736582/199821097-3028e90f-30b1-4461-920b-ad88a1a47ec2.png)

Figma Design
![titleheadline](https://user-images.githubusercontent.com/26736582/199821155-4b02d703-284c-41b2-a3ee-8652a7fd74b7.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
:red_circle: Kindly also adapt the border radius at the bottom left  section to match the Figma design

Your Design

![borderradius](https://user-images.githubusercontent.com/26736582/199821564-8a5ba547-de3c-48d5-baf2-6df4c4c5663e.png)


Figma Design

![borderfigma](https://user-images.githubusercontent.com/26736582/199821590-d1a56f43-b67c-4f13-81de-d0216531c3b7.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
> +        <h2 class="primary-text">About Myself</h2>
:red_circle:  Please make sure you move  `Myself` to a new line you can insert a` <br>` tag between `About` and `Myself` to insert a single line break. Your final code will look like this `About <br> Myself`

Your Design

![titleStudent](https://user-images.githubusercontent.com/26736582/199821802-ed67aac5-39a4-4adc-b90f-ab35737676d2.png)

Figma Design

![titlefigma](https://user-images.githubusercontent.com/26736582/199821776-eb6f5355-ed53-418b-a4c8-94f88a82180f.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
> +              <li>Languages</li>
:red_circle: Please make sure you pick the right font color from the Figma template. As for now, Your font color does not reflect the font color in the Figma Design

Your Design
![fontcolorstudent](https://user-images.githubusercontent.com/26736582/199822096-efeacab7-44da-44f0-84e8-4f3d743e2698.png)


Figma Design

![fontcolor](https://user-images.githubusercontent.com/26736582/199822021-6874e374-5f77-47aa-af5f-60838408cb86.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
> +          </li>
:red_circle:   Kindly reduce your cards' width and leave some room at the right of the languages list to match the Figma design

Your Design
![tech](https://user-images.githubusercontent.com/26736582/199823114-a56ccd61-0232-487a-a4e8-893be4e26b0e.png)

Figma Design
![tecnologie list](https://user-images.githubusercontent.com/26736582/199822740-b1a7ed5e-3934-40d5-b72e-f467d06a4048.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on index.html
> +            <ul class="hidden-options-title">
- [ ] :red_circle:  As you can see from the Figma design, there is a top margin between the technology categories( Frameworks) and the languages list.  Kindly fix this to match the Figma design

Your Design
![nospace](https://user-images.githubusercontent.com/26736582/199823551-8627c1f9-f86c-448e-b07b-83079ab6940f.png)

Figma Design
![spacing](https://user-images.githubusercontent.com/26736582/199823600-92220f42-c344-419c-8ee3-46ad31394bf5.png)

2022-11-03 20:38 UTC, bienvenuushindi commented on style.css
> +@media (min-width: 768px) {
- [ ] :red_circle:  The mobile version of your portfolio seems to be affected by the modifications you have made. Kindly try to fix these issues. 
  -  The content does not fit and you have to use the horizontal scroll bar to see everything
  -  Please make sure you set a fixed width on each image in your cards.
  -  Please make sure on the mobile screen, only the hamburger menu appears and not the menu items


Your Mobile version

![affectected](https://user-images.githubusercontent.com/26736582/199824161-5c288d37-a2f5-41bd-a522-9d4f5fe127d5.gif)

2022-11-04 18:14 UTC, aimalamiri approved these changes
Hi @KMT-Media, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ApprovedDavieGIF](https://user-images.githubusercontent.com/34779928/191333120-c0c2ce83-28e1-4dbc-aac1-09e467f7a8bd.gif)


## Highlights

- The desktop version is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 18:58 UTC, merged